#Used for zero-shot test

train_file: ['/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/en/captions_rationales_subquestions/train_30000_captions_rationales_subquestions_final.json',]
valid_file: ['/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/en/captions_rationales_subquestions/valid_captions_rationales_subquestions_final.json']

answer_list: 'iglue/datasets/gqa/annotations/trainval_ans2label.json'
vqa_root: 'images/gqa/'


# zero-shot test set
test_file: {
  'bn': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/bn/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'de': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/de/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'en': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/en/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'id': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/id/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'ko': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/ko/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'pt': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/pt/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'ru': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/ru/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
  'zh': [ '/data/tir/projects/tir6/general/piyushkh/xGQA/multimodal-crosslingual-vqa/idea2/data/zh/captions_rationales_subquestions/test_captions_rationales_subquestions_final.json',
          'iglue/datasets/gqa/annotations/trainval_ans2label.json' ],
}


## Vision Encoder
# vision_config: 'configs/config_swinB_384.json'
vision_config: 'configs/config_swinB_224.json'


use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
# image_res: 384
image_res: 224
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12


## Training
num_dec_layers: 6
batch_size_train: 1
batch_size_test: 4
max_tokens: 512
k_test: 128


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 5, num_warmup_steps: 0.1}
start_eval: 2  # epoch index


